### PR TITLE
Renaming update and cleaning up project

### PR DESCRIPTION
**Pull request by vinchan**

### CODE REVIEW

**Comment by vinchan** [comment]
@kaysabelle or @jeslin :
Please remove all connect stream related UI/functionality (I commented out the js for it)

@MinickLS Please try avoid using dumpLog/console.log too much in plugin, use the callback failure instead, since there's no gaurantee the user would have a "dumpLog" in their index.js.

**Comment by vinchan** [comment]
Also random 1-liner incase anyone missed, but barcode scanner should've been broken from the latest push. This pull request fixed the error.

**Comment by vinchan** [comment]
Since there is no longer a differentiation between stream and parse, might want to rename the buttons and functions so that it just says "Connect" or something, as opposed to "Get Parsed Data", or maybe just call it "Get Data".

**Comment by katrina** [comment]
I don't think you meant to tag the person with username 'katrina' in this thread.  Please remove me.

**Comment by kaysabelle** [comment]
This looks good to me, I can make the appropriate UI changes in my next pull request.

**Comment by MinickLS** [comment]
Merging...

**Pull request merged**
